# Generated by Django 2.2.16 on 2020-09-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_second_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GclidClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
