# Generated by Django 2.2.16 on 2020-09-27 11:42

from django.db import migrations


def populate_db(apps, schema_editor):
    User = apps.get_model("user", "User")
    print('populate_db')


def depopulate_db(apps, schema_editor):
    print('depopulate_db')


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_gclidclick'),
    ]

    operations = [
        migrations.RunPython(populate_db, depopulate_db)
    ]
